[package]
name = "rust-nix"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atom_syndication = "0.11"
reqwest = "0.11"
anyhow = "1.0.55"
tokio = { version = "1.17.0", features = ["full"] }